#!/bin/bash
#================
# FILE          : linuxrc
#----------------
# PROJECT       : OpenSuSE KIWI Image System
# COPYRIGHT     : (c) 2006 SUSE LINUX Products GmbH. All rights reserved
#               :
# AUTHOR        : Marcus Schaefer <ms@suse.de>
#               :
# BELONGS TO    : Operating System images
#               :
# DESCRIPTION   : This file is changed to become the real
#               : linuxrc script which is used to prepare the
#               : operating system for the main image
#               :
#               :
# STATUS        : BETA
#----------------
#======================================
# Exports (General)
#--------------------------------------
export PATH="/sbin:/bin:/usr/sbin:/usr/bin"
export IFS_ORIG=$IFS
export ARCH=`arch`
export DEBUG=0

#======================================
# Functions
#--------------------------------------
. /include

#======================================
# mount filesystems and start udev
#--------------------------------------
mountSystemFilesystems &>/dev/null
udevStart

#======================================
# include kernel params to env
#--------------------------------------
includeKernelParameters

#======================================
# Shell
#--------------------------------------
while true;do
	systemException "Yo Mama" "shell"
done

